NicoleBusiness/Models/ApiResult.cs
using Microsoft.AspNetCore.Mvc;

namespace NicoleBusiness.Models
{
    public class ApiResult
    {
        public bool Success { get; set; }
        public string Message { get; set; }
        public object Object { get; set; }
        
    }
}

NicoleBusiness/Models/ErrorViewModel.cs
using System;

namespace NicoleBusiness.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NicoleBusiness/Models/Expense.cs
using System;
namespace NicoleBusiness.Models
{
    public class Expense
    {
        public int Id { get; set; }
        public int TransactionTypeId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public bool TaxWriteOff { get; set; }
        public DateTime TransactionDate { get; set; }
    }
}

NicoleBusiness/Models/Income.cs
using System;
namespace NicoleBusiness.Models
{
    public class Income
    {
        public int Id { get; set; }
        public int TransactionTypeId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public DateTime TransactionDate { get; set; }
    }
}

NicoleBusiness/Models/NicoleBusinessDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace NicoleBusiness.Models
{
    public partial class NicoleBusinessDbContext : DbContext
    {
        public virtual DbSet<Income> Income { get; set; }
        public virtual DbSet<Expense> Expense { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }


        public NicoleBusinessDbContext(DbContextOptions<NicoleBusinessDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
//                modelBuilder.Entity<>(entity =>
//                {
//                    entity.Property(e => e.Url).IsRequired();
//                });
//
//                modelBuilder.Entity<Post>(entity =>
//                {
//                    entity.HasOne(d => d.Blog)
//                        .WithMany(p => p.Post)
//                        .HasForeignKey(d => d.BlogId);
//                });
        }
    }
}

NicoleBusiness/Models/TransactionType.cs
using System;
namespace NicoleBusiness.Models
{
    public class TransactionType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreationDate { get; set; }
    }
}

NicoleBusiness/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using NicoleBusiness.Contracts;
using NicoleBusiness.Models;

namespace NicoleBusiness.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _expenseService;

        public ExpenseController(IExpenseService expenseService)
        {
            _expenseService = expenseService;
        }

        public IActionResult EnterExpense(Expense model)
        {
            _expenseService.CreateExpense(model);
            return View("/Views/Expense/Expense.cshtml");
        }
    }
}

NicoleBusiness/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NicoleBusiness.Models;

namespace NicoleBusiness.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Income()
        {
            ViewData["Message"] = "Your application description page.";

            return View("/Views/Income/Income.cshtml");
        }
        
        public IActionResult Expense()
        {
            ViewData["Message"] = "Your application description page.";

            return View("/Views/Expense/Expense.cshtml");
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NicoleBusiness/Controllers/IncomeController.cs
using Microsoft.AspNetCore.Mvc;
using NicoleBusiness.Models;
using NicoleBusiness.Contracts;

namespace NicoleBusiness.Controllers
{
    public class IncomeController : Controller
    {
        private readonly IIncomeService _incomeService;
        
        public IncomeController(IIncomeService incomeService)
        {
            _incomeService = incomeService;
        }

        public IActionResult EnterIncome(Income model)
        {
            ViewData["Message"] = "Your application description page.";
            _incomeService.Add(model);
            return View("/Views/Income/Income.cshtml");
        }
    }
}

NicoleBusiness/Controllers/TransactionTypeController.cs
using Microsoft.AspNetCore.Mvc;
using NicoleBusiness.Contracts;
using NicoleBusiness.Models;

namespace NicoleBusiness.Controllers
{
    public class TransactionTypeController : Controller
    {
        private readonly ITransactionTypeService _transactionTypeService;

        public TransactionTypeController(ITransactionTypeService transactionTypeService)
        {
            _transactionTypeService = transactionTypeService;
        }

        public IActionResult CreateTransactionType(TransactionType transactionType)
        {
            var result = _transactionTypeService.CreateTransactionType(transactionType);
            return result.Success ? Ok(result) : StatusCode(500, result);
        }

        public IActionResult DeleteTransactionType(string transactionTypeName)
        {
            var result = _transactionTypeService.DeleteTransactionType(transactionTypeName);
            return result.Success ? Ok(result) : StatusCode(500, result);
        }

        public IActionResult GetTransactionType()
        {
            var result = _transactionTypeService.GetTransactionType();
            return result.Success ? Ok(result) : StatusCode(500, result);
        }
    }
}

NicoleBusiness/Views/Expense/Expense.cshtml
@model Expense
@{
    ViewData["Title"] = "Enter Expense";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<form asp-controller="Expense" asp-action="EnterExpense" method="post">

    <label class="mr-sm-2">Transaction Type</label>
    <select class="btn btn-secondary dropdown-toggle" id="transaction-type">
        <option selected>Choose...</option>
        <option value="1">One</option>
        <option value="2">Two</option>
        <option value="3">Three</option>
    </select>

    <button type="button" class="btn btn-primary">Add Type</button>

    <div class="input-group">
        <span class="input-group-addon">$</span>
        <input type="text" asp-for="Amount" name="amount" class="form-control" aria-label="Amount (to the nearest dollar)">
        <span class="input-group-addon">.00</span>
    </div>

    <div class="form-group">
        <label for="Expense-description" class="col-2 col-form-label">Description</label>
        <textarea asp-for="Description" name="description" class="form-control" id="expense-description" rows="3"></textarea>
    </div>

    <div class="form-group">
        <label for="transaction-date-input" class="col-2 col-form-label">Date</label>
        <div class="col-10">
            <input asp-for="TransactionDate" name="transaction-date" class="form-control" type="date" value="2011-08-19" id="example-date-input">
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Enter Expense</button>
</form>


@section scripts{
    <script src="~/js/transaction-type.js"></script>
}

NicoleBusiness/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NicoleBusiness/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

NicoleBusiness/Views/Income/Income.cshtml
@model Income
@{
    ViewData["Title"] = "Enter Income";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<form asp-controller="Income" asp-action="EnterIncome" method="post">

    <label class="mr-sm-2">Transaction Type</label>
    <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="transaction-type">
        <option selected>Choose...</option>
    </select>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add Type</button>

    <div class="input-group">
        <span class="input-group-addon">$</span>
        <input type="text" asp-for="Amount" name="amount" class="form-control" aria-label="Amount (to the nearest dollar)">
        <span class="input-group-addon">.00</span>
    </div>

    <div class="form-group">
        <label for="income-description" class="col-2 col-form-label">Description</label>
        <textarea asp-for="Description" name="description" class="form-control" id="income-description" rows="3"></textarea>
    </div>

    <div class="form-group">
        <label for="transaction-date-input" class="col-2 col-form-label">Date</label>
        <div class="col-10">
            <input asp-for="TransactionDate" name="transaction-date" class="form-control" type="date" value="2011-08-19" id="example-date-input">
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Enter Income</button>
</form>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">

                <div class="panel panel-default">
                    <!-- Table -->
                    <table class="table" id="transaction-add-remove-table">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Remove</th>
                        </tr>
                    </table>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script src="~/js/transaction-type.js"></script>
}

NicoleBusiness/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NicoleBusiness</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NicoleBusiness</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Income">Income</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Expense">Expense</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - NicoleBusiness</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

NicoleBusiness/Views/TranactionType/TransactionTypeModal.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>